<div style="background-color:darkseagreen; padding: 18px; border-radius: 3px; text-align:center; font-size:2.5em; font-weight:bold; color:#222; margin-bottom:25px; letter-spacing:1px;">
Predicting Donor Response for Social Good 
</div>


# <h2 style="border-bottom: 4px solid darkseagreen; width:fit-content; margin: 0 auto 25px auto; padding-bottom:6px; font-weight:bold;">Exploratory Data Analysis</h2>

_Data Mining II 2025/2026_

Project by:
Francisco Gomes (20221810), Margarida Marchão (20221901), Marta Alves (20221890), Pedro Coimbras (20211573)

 ## <h3 style="border-bottom: 4px solid darkseagreen; margin: 0 0 25px 0; padding-bottom:6px; font-weight:bold; font-size:1.7em;text-align:left;">1.  Importing Needed libraries and data</h3>

In [1]:
#import needed libraries

#general use
import pandas as pd
import numpy as np

#visualization
import matplotlib as plt
import seaborn as sns



#importing util functions
from utils.utils_eda import *

In [2]:
#import training data
data = pd.read_csv('project_data\donors_train.csv', index_col=0)


## <h3 style="border-bottom: 4px solid darkseagreen; margin: 0 0 25px 0; padding-bottom:6px; font-weight:bold; text-align:left;font-size:1.7em">2. Exploratory Data Analysis</h3>

### <h4 style=" margin: 0 0 25px 0; padding-bottom:6px; font-weight:bold; text-align:left;">2.1 Dataset overview</h4>



Checking the main attributes of this dataset, such as shape, features and feature types

Metadata

| **Feature Group** | Feature Name | Description |
|---|---|---|
| **Target** | TARGET_B | Donated last year campaign (1/0) |
| **Identifier** | CONTROL_NUMBER | Unique donor identifier |
| **Demographics** | DONOR_AGE | Donor age at last solicitation |
| | DONOR_GENDER | Gender of donor |
| | CHILDREN | Number of children |
| | URBANICITY | Urban/rural area code |
| | SES | Socioeconomic status group (1-5) |
| | HOME_OWNER | Homeownership status (H/U) |
| | INCOME_GROUP | Income group code (1-7) |
| | WEALTH_RATING | Wealth rating group (1-10) |
| **Neighborhood** | MEDIAN_HOME_VALUE | Median home value ($100s) |
| | MEDIAN_HOUSEHOLD_INCOME | Median household income ($100s) |
| | PCT_OWNER_OCCUPIED | % owner-occupied homes nearby |
| | PER_CAPITA_INCOME | Per capita neighborhood income |
| | PCT_ATTRIBUTE1 | % male active military in neighborhood |
| | PCT_ATTRIBUTE2 | % male veterans in neighborhood |
| | PCT_ATTRIBUTE3 | % Vietnam veterans in neighborhood |
| | PCT_ATTRIBUTE4 | % WW2 veterans in neighborhood |
| **Donor Status** | PEP_STAR | STAR status for 3 consecutive donations |
| | RECENT_STAR_STATUS | STAR in last 4 years |
| | RECENCY_STATUS_96NK | Donor recent activity group (A/E/F/L/N/S) |
| | FREQUENCY_STATUS_97NK | Donations count in last period |
| **Recent Giving** | RECENT_RESPONSE_PROP | Prop. of responses to solicitations |
| | RECENT_AVG_GIFT_AMT | Avg. donation amount (last 4 years) |
| | RECENT_CARD_RESPONSE_PROP | Prop. card responses (last 4 years) |
| | RECENT_AVG_CARD_GIFT_AMT | Avg. card donation (last 4 years) |
| | RECENT_RESPONSE_COUNT | Responses to promos (last 4 years) |
| | RECENT_CARD_RESPONSE_COUNT | Card solicitation responses (last 4 yrs) |
| **Recency/Frequency** | MONTHS_SINCE_LAST_PROM_RESP | Months since last promo response |
| | MONTHS_SINCE_LAST_GIFT | Months since last donation |
| | MONTHS_SINCE_FIRST_GIFT | Months since first donation |
| **Lifetime Giving** | LIFETIME_CARD_PROM | Lifetime card promos sent |
| | LIFETIME_PROM | Lifetime total promos sent |
| | LIFETIME_GIFT_AMOUNT | Total donated amount (lifetime) |
| | LIFETIME_GIFT_COUNT | Total donations (lifetime) |
| | LIFETIME_MAX_GIFT_AMT | Max gift amount (lifetime) |
| | LIFETIME_MIN_GIFT_AMT | Min gift amount (lifetime) |
| **Recent Giving** | LAST_GIFT_AMT | Amount of most recent donation |
| | CARD_PROM_12 | Card promos sent (last 12 months) |
| | NUMBER_PROM_12 | Total promos sent (last 12 months) |
| **Giving Profiles** | FILE_CARD_GIFT | Lifetime avg. card donation amount |

#### *2.1.1 Summary Statistics*
Getting a general understanding of tendencies and data spread

In [3]:
pd.set_option("display.max_columns", None)

data.head()

,CARD_PROM_12,CHILDREN,DONOR_AGE,DONOR_GENDER,FILE_CARD_GIFT,FREQUENCY_STATUS_97NK,HOME_OWNER,INCOME_GROUP,LAST_GIFT_AMT,LIFETIME_CARD_PROM,LIFETIME_GIFT_AMOUNT,LIFETIME_GIFT_COUNT,LIFETIME_MAX_GIFT_AMT,LIFETIME_MIN_GIFT_AMT,LIFETIME_PROM,MEDIAN_HOME_VALUE,MEDIAN_HOUSEHOLD_INCOME,MONTHS_SINCE_FIRST_GIFT,MONTHS_SINCE_LAST_GIFT,MONTHS_SINCE_LAST_PROM_RESP,NUMBER_PROM_12,PCT_ATTRIBUTE1,PCT_ATTRIBUTE2,PCT_ATTRIBUTE3,PCT_ATTRIBUTE4,PCT_OWNER_OCCUPIED,PEP_STAR,PER_CAPITA_INCOME,RECENCY_STATUS_96NK,RECENT_AVG_CARD_GIFT_AMT,RECENT_AVG_GIFT_AMT,RECENT_CARD_RESPONSE_COUNT,RECENT_CARD_RESPONSE_PROP,RECENT_RESPONSE_COUNT,RECENT_RESPONSE_PROP,RECENT_STAR_STATUS,SES,URBANICITY,WEALTH_RATING,TARGET_B
CONTROL_NUMBER,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
61745,4.0,3.0,33.0,M,0.0,1.0,H,5.0,20.0,9.0,35.0,2.0,20.0,15.0,21.0,566.0,315.0,182.037132,18.0,18.0,10.0,0.0,52.0,17.0,25.0,92.0,0.0,12827.0,A,0.00,17.50,NaN,0.000,2.0,0.154,0.0,2,T,NaN,1
112703,3.0,2.0,NaN,F,1.0,1.0,U,NaN,15.0,6.0,15.0,1.0,15.0,15.0,15.0,318.0,148.0,24.000000,24.0,24.0,7.0,0.0,31.0,31.0,39.0,73.0,0.0,7787.0,N,15.00,15.00,1.0,0.250,1.0,0.100,0.0,3,R,NaN,1
166437,4.0,2.0,NaN,F,7.0,3.0,H,4.0,10.0,17.0,79.0,11.0,12.0,5.0,40.0,1669.0,373.0,129.000000,15.0,15.0,8.0,0.0,26.0,39.0,38.0,84.0,1.0,13965.0,S,0.00,10.67,0.0,0.000,3.0,0.231,1.0,1,U,NaN,0
170621,4.0,NaN,61.0,M,13.0,1.0,H,6.0,11.0,28.0,80.0,17.0,11.0,3.0,75.0,1464.0,488.0,130.000000,16.0,16.0,13.0,0.0,48.0,30.0,44.0,84.0,1.0,24123.0,A,10.00,10.00,2.0,0.286,2.0,0.111,0.0,1,U,NaN,0
44428,6.0,0.0,75.0,M,3.0,4.0,H,3.0,7.0,9.0,27.0,5.0,7.0,5.0,22.0,936.0,249.0,24.000000,17.0,17.0,13.0,0.0,52.0,NaN,66.0,90.0,1.0,15008.0,N,5.67,5.40,3.0,0.600,5.0,0.500,0.0,2,C,NaN,0

In [4]:
#check dataset shape
display(data.shape)

#check if index values are unique
is_unique = data.index.is_unique
print(f"Are index values unique? {is_unique}, with {len(data.index.unique())} out of {data.shape[0]} unique values.")

(13560, 40)

Are index values unique? True, with 13560 out of 13560 unique values.

Each record in the dataset corresponds to **one registered donor in the Civic Support Alliance database**, including both demographic and donation-related information

In [5]:
data.describe()

,CARD_PROM_12,CHILDREN,DONOR_AGE,FILE_CARD_GIFT,FREQUENCY_STATUS_97NK,INCOME_GROUP,LAST_GIFT_AMT,LIFETIME_CARD_PROM,LIFETIME_GIFT_AMOUNT,LIFETIME_GIFT_COUNT,LIFETIME_MAX_GIFT_AMT,LIFETIME_MIN_GIFT_AMT,LIFETIME_PROM,MEDIAN_HOME_VALUE,MEDIAN_HOUSEHOLD_INCOME,MONTHS_SINCE_FIRST_GIFT,MONTHS_SINCE_LAST_GIFT,MONTHS_SINCE_LAST_PROM_RESP,NUMBER_PROM_12,PCT_ATTRIBUTE1,PCT_ATTRIBUTE2,PCT_ATTRIBUTE3,PCT_ATTRIBUTE4,PCT_OWNER_OCCUPIED,PEP_STAR,PER_CAPITA_INCOME,RECENT_AVG_CARD_GIFT_AMT,RECENT_AVG_GIFT_AMT,RECENT_CARD_RESPONSE_COUNT,RECENT_CARD_RESPONSE_PROP,RECENT_RESPONSE_COUNT,RECENT_RESPONSE_PROP,RECENT_STAR_STATUS,WEALTH_RATING,TARGET_B
count,13297.000000,13298.000000,10006.000000,13300.000000,13278.000000,10271.000000,13299.000000,13300.000000,13287.000000,13285.000000,13300.000000,13279.000000,13306.000000,13294.000000,13290.000000,13290.000000,13292.000000,13115.000000,13289.000000,13286.000000,13299.000000,13288.000000,13295.000000,13292.000000,13292.000000,13289.000000,13289.000000,13292.000000,13294.000000,13285.000000,13291.000000,13285.000000,13303.000000,7290.000000,13560.000000
mean,5.379945,1.996802,58.814086,5.242995,1.993986,3.923575,16.639062,18.649742,104.883094,9.989321,19.209922,7.670698,47.566160,1081.099146,342.714746,69.185820,18.215220,19.047722,12.917143,1.079089,30.646003,29.592675,32.858382,69.649793,0.507133,15917.009156,11.745549,15.405034,1.735560,0.231370,3.046092,0.190760,0.903545,4.999967,0.250000
std,1.317190,1.466203,17.568008,4.833704,1.147577,1.957765,12.952247,8.936163,112.121470,9.096504,15.917684,8.592010,23.990434,1004.015872,172.478153,38.994749,4.169467,3.546799,4.859490,5.402809,11.917120,15.752201,18.561128,22.459383,0.514010,9174.923246,11.452423,10.617418,1.609212,0.194583,2.133374,0.119291,2.630881,2.999420,0.433029
min,1.000000,-2.299824,0.000000,-10.098570,-1.363824,-1.737977,-21.833600,-7.205341,-243.255927,-18.629060,-33.606782,-19.515952,-23.208888,-2187.526674,-190.662683,-48.817879,4.000000,-12.000000,-2.154264,-15.109374,-3.918837,-17.245877,-22.613054,0.000000,-0.529872,-12823.750149,-22.840188,-16.817445,-3.695219,-0.368988,-3.249437,-0.181529,-7.809473,-3.752821,0.000000
25%,5.000000,1.000000,46.000000,2.000000,1.000000,2.000000,10.000000,11.000000,41.000000,4.000000,12.000000,3.000000,28.000000,517.000000,232.000000,33.000000,16.000000,17.000000,11.000000,0.000000,25.000000,20.000000,21.000000,59.000000,0.000000,10887.000000,5.000000,10.000000,1.000000,0.100000,2.000000,0.105000,0.000000,3.000000,0.000000
50%,6.000000,2.000000,60.000000,4.000000,2.000000,4.000000,15.000000,18.000000,80.000000,8.000000,16.000000,5.000000,47.000000,753.000000,312.000000,65.000000,18.000000,18.000000,12.000000,0.000000,31.000000,29.000000,32.000000,76.000000,1.000000,13880.000000,10.500000,14.225000,1.000000,0.200000,3.000000,0.167000,0.000000,5.000000,0.000000
75%,6.000000,3.000000,73.000000,8.000000,3.000000,5.000000,20.000000,26.000000,133.000000,14.000000,21.000000,10.000000,64.000000,1247.000000,420.000000,104.000000,20.000000,21.000000,13.000000,0.000000,37.000000,39.000000,43.000000,85.000000,1.000000,18434.000000,16.000000,20.000000,2.000000,0.333000,4.000000,0.250000,1.000000,8.000000,0.250000
max,17.000000,6.220526,108.946450,32.000000,5.279946,9.503280,450.000000,55.000000,3775.000000,95.000000,600.000000,450.000000,194.000000,6000.000000,1500.000000,260.000000,30.290180,36.000000,64.000000,97.000000,85.000000,99.000000,99.000000,134.837044,2.004585,174523.000000,300.000000,260.000000,9.000000,1.000000,16.000000,1.000000,22.000000,13.451898,1.000000

*KEY INSIGHTS*
- A lot of variables present highly inconsitent values, such as negative values where these aren't possible and max values beyond comprehension,
- The target variable shows an average value of 0.25, telling us that only one in around 4 people have responded to the call for donations

#### *2.1.2 Features and Feature Types*
Understanding data types in the dataset and their influence in this project

In [6]:
#checking data format and null count
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13560 entries, 61745 to 45722
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CARD_PROM_12                 13297 non-null  float64
 1   CHILDREN                     13298 non-null  float64
 2   DONOR_AGE                    10006 non-null  float64
 3   DONOR_GENDER                 13288 non-null  object
 4   FILE_CARD_GIFT               13300 non-null  float64
 5   FREQUENCY_STATUS_97NK        13278 non-null  float64
 6   HOME_OWNER                   13274 non-null  object
 7   INCOME_GROUP                 10271 non-null  float64
 8   LAST_GIFT_AMT                13299 non-null  float64
 9   LIFETIME_CARD_PROM           13300 non-null  float64
 10  LIFETIME_GIFT_AMOUNT         13287 non-null  float64
 11  LIFETIME_GIFT_COUNT          13285 non-null  float64
 12  LIFETIME_MAX_GIFT_AMT        13300 non-null  float64
 13  LIFETIME_MIN_GIFT_AMT        13279 non-null  float64
 14  LIFETIME_PROM                13306 non-null  float64
 15  MEDIAN_HOME_VALUE            13294 non-null  float64
 16  MEDIAN_HOUSEHOLD_INCOME      13290 non-null  float64
 17  MONTHS_SINCE_FIRST_GIFT      13290 non-null  float64
 18  MONTHS_SINCE_LAST_GIFT       13292 non-null  float64
 19  MONTHS_SINCE_LAST_PROM_RESP  13115 non-null  float64
 20  NUMBER_PROM_12               13289 non-null  float64
 21  PCT_ATTRIBUTE1               13286 non-null  float64
 22  PCT_ATTRIBUTE2               13299 non-null  float64
 23  PCT_ATTRIBUTE3               13288 non-null  float64
 24  PCT_ATTRIBUTE4               13295 non-null  float64
 25  PCT_OWNER_OCCUPIED           13292 non-null  float64
 26  PEP_STAR                     13292 non-null  float64
 27  PER_CAPITA_INCOME            13289 non-null  float64
 28  RECENCY_STATUS_96NK          13298 non-null  object
 29  RECENT_AVG_CARD_GIFT_AMT     13289 non-null  float64
 30  RECENT_AVG_GIFT_AMT          13292 non-null  float64
 31  RECENT_CARD_RESPONSE_COUNT   13294 non-null  float64
 32  RECENT_CARD_RESPONSE_PROP    13285 non-null  float64
 33  RECENT_RESPONSE_COUNT        13291 non-null  float64
 34  RECENT_RESPONSE_PROP         13285 non-null  float64
 35  RECENT_STAR_STATUS           13303 non-null  float64
 36  SES                          13287 non-null  object
 37  URBANICITY                   13291 non-null  object
 38  WEALTH_RATING                7290 non-null   float64
 39  TARGET_B                     13560 non-null  int64
dtypes: float64(34), int64(1), object(5)
memory usage: 4.7+ MB

Reducing the memory alocation of numerical features to enable faster processing

In [ ]:
#Reducing float64 to float32 and int64 to int32
data = reduce_memory_usage(data)
data.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
Index: 13560 entries, 61745 to 45722
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CARD_PROM_12                 13297 non-null  float32
 1   CHILDREN                     13298 non-null  float32
 2   DONOR_AGE                    10006 non-null  float32
 3   DONOR_GENDER                 13288 non-null  object
 4   FILE_CARD_GIFT               13300 non-null  float32
 5   FREQUENCY_STATUS_97NK        13278 non-null  float32
 6   HOME_OWNER                   13274 non-null  object
 7   INCOME_GROUP                 10271 non-null  float32
 8   LAST_GIFT_AMT                13299 non-null  float32
 9   LIFETIME_CARD_PROM           13300 non-null  float32
 10  LIFETIME_GIFT_AMOUNT         13287 non-null  float32
 11  LIFETIME_GIFT_COUNT          13285 non-null  float32
 12  LIFETIME_MAX_GIFT_AMT        13300 non-null  float32
 13  LIFETIME_MIN_GIFT_AMT        13279 non-null  float32
 14  LIFETIME_PROM                13306 non-null  float32
 15  MEDIAN_HOME_VALUE            13294 non-null  float32
 16  MEDIAN_HOUSEHOLD_INCOME      13290 non-null  float32
 17  MONTHS_SINCE_FIRST_GIFT      13290 non-null  float32
 18  MONTHS_SINCE_LAST_GIFT       13292 non-null  float32
 19  MONTHS_SINCE_LAST_PROM_RESP  13115 non-null  float32
 20  NUMBER_PROM_12               13289 non-null  float32
 21  PCT_ATTRIBUTE1               13286 non-null  float32
 22  PCT_ATTRIBUTE2               13299 non-null  float32
 23  PCT_ATTRIBUTE3               13288 non-null  float32
 24  PCT_ATTRIBUTE4               13295 non-null  float32
 25  PCT_OWNER_OCCUPIED           13292 non-null  float32
 26  PEP_STAR                     13292 non-null  float32
 27  PER_CAPITA_INCOME            13289 non-null  float32
 28  RECENCY_STATUS_96NK          13298 non-null  object
 29  RECENT_AVG_CARD_GIFT_AMT     13289 non-null  float32
 30  RECENT_AVG_GIFT_AMT          13292 non-null  float32
 31  RECENT_CARD_RESPONSE_COUNT   13294 non-null  float32
 32  RECENT_CARD_RESPONSE_PROP    13285 non-null  float32
 33  RECENT_RESPONSE_COUNT        13291 non-null  float32
 34  RECENT_RESPONSE_PROP         13285 non-null  float32
 35  RECENT_STAR_STATUS           13303 non-null  float32
 36  SES                          13287 non-null  object
 37  URBANICITY                   13291 non-null  object
 38  WEALTH_RATING                7290 non-null   float32
 39  TARGET_B                     13560 non-null  int32
dtypes: float32(34), int32(1), object(5)
memory usage: 6.1 MB


### <h4 style=" margin: 0 0 25px 0; padding-bottom:6px; font-weight:bold; text-align:left;">2.2 Data Validation</h4>
Exploring data quality by analysing inconsistencies, missing values, outliers, and correlations

#### *2.2.1 Incoherences Analysis*

#### *2.2.2 Feature Correlation*

#### *2.2.3 Missing value Analysis*
Checking the frequency and correlation of missing values across the dataset

In [8]:
#Visualising the absolute and relative amount of missing values in each feature
missing_counts = data.isna().sum()
missing_percent = (missing_counts / len(data)) * 100

missing_df = pd.DataFrame({
    'Missing Values': missing_counts.values,
    'Percent Missing': missing_percent.values
}, index=missing_counts.index)

missing_df = missing_df.sort_values(by='Percent Missing', ascending=False)

missing_df

                             Missing Values  Percent Missing
WEALTH_RATING                          6270        46.238938
DONOR_AGE                              3554        26.209440
INCOME_GROUP                           3289        24.255162
MONTHS_SINCE_LAST_PROM_RESP             445         3.281711
HOME_OWNER                              286         2.109145
FREQUENCY_STATUS_97NK                   282         2.079646
LIFETIME_MIN_GIFT_AMT                   281         2.072271
LIFETIME_GIFT_COUNT                     275         2.028024
RECENT_CARD_RESPONSE_PROP               275         2.028024
RECENT_RESPONSE_PROP                    275         2.028024
PCT_ATTRIBUTE1                          274         2.020649
LIFETIME_GIFT_AMOUNT                    273         2.013274
SES                                     273         2.013274
PCT_ATTRIBUTE3                          272         2.005900
DONOR_GENDER                            272         2.005900
RECENT_AVG_CARD_GIFT_AMT                271         1.998525
NUMBER_PROM_12                          271         1.998525
PER_CAPITA_INCOME                       271         1.998525
MONTHS_SINCE_FIRST_GIFT                 270         1.991150
MEDIAN_HOUSEHOLD_INCOME                 270         1.991150
URBANICITY                              269         1.983776
RECENT_RESPONSE_COUNT                   269         1.983776
RECENT_AVG_GIFT_AMT                     268         1.976401
PCT_OWNER_OCCUPIED                      268         1.976401
MONTHS_SINCE_LAST_GIFT                  268         1.976401
PEP_STAR                                268         1.976401
RECENT_CARD_RESPONSE_COUNT              266         1.961652
MEDIAN_HOME_VALUE                       266         1.961652
PCT_ATTRIBUTE4                          265         1.954277
CARD_PROM_12                            263         1.939528
RECENCY_STATUS_96NK                     262         1.932153
CHILDREN                                262         1.932153
PCT_ATTRIBUTE2                          261         1.924779
LAST_GIFT_AMT                           261         1.924779
FILE_CARD_GIFT                          260         1.917404
LIFETIME_CARD_PROM                      260         1.917404
LIFETIME_MAX_GIFT_AMT                   260         1.917404
RECENT_STAR_STATUS                      257         1.895280
LIFETIME_PROM                           254         1.873156
TARGET_B                                  0         0.000000

Preleminary conclusions:
- Seems like the only 2 columns that **do not** contain missing values are those relating to the customer ID and to the target variable (which explicits if the given person will donate)
- Some columns, like *WEALTH_RATING*, *DONOR_AGE*, *INCOME_GROUP* present a rate of missing values close or even higher than 25%, maybe requiring imputation or removal
- There are several groups of columns presenting the exact same number of missing values, suggesting that these features might be related and missing not at random.

<div style="color: red;">Alterar esta parte, acho que esta função nao e a mais adequada:</div>

In [9]:
#analysing missing values correlation

#removing WEALTH_RATING as its overwelming amount of missing values would trow off the conclusion
data_no_wealth = data.drop(["WEALTH_RATING"], axis = 1)

cols_missing = [col for col in data_no_wealth.columns if col != ["TARGET_B"]]
missing_summary = analyze_missingness_patterns(data_no_wealth, cols_missing)

Pairwise Missingness Correlation Matrix:

C:\Users\marga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pandas\io\formats\style.py:3807: RuntimeWarning: All-NaN slice encountered
  smin = np.nanmin(gmap) if vmin is None else vmin
C:\Users\marga\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pandas\io\formats\style.py:3808: RuntimeWarning: All-NaN slice encountered
  smax = np.nanmax(gmap) if vmax is None else vmax

 Top 10 Pairs with Highest Overlapping Missing Values:

                                          count
DONOR_AGE    INCOME_GROUP                  1902
             MONTHS_SINCE_LAST_PROM_RESP    108
INCOME_GROUP MONTHS_SINCE_LAST_PROM_RESP     97
DONOR_AGE    MONTHS_SINCE_LAST_GIFT          92
             PEP_STAR                        90
             LIFETIME_MIN_GIFT_AMT           89
INCOME_GROUP LIFETIME_MIN_GIFT_AMT           86
DONOR_AGE    PCT_ATTRIBUTE2                  82
             DONOR_GENDER                    82
DONOR_GENDER INCOME_GROUP                    80

#### *2.2.4 Outlier Analysis*